FROM node:alpine as build-stage
WORKDIR /app
COPY package.json ./
RUN npm install
COPY ./ /app/
RUN npm run build

FROM nginx:1.23
COPY --from=build-stage /app/build /etc/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
